/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AirportPickupRouteImport } from './routes/airport-pickup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AuthenticatedPartnerRouteImport } from './routes/_authenticated/partner'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as ApiRazorpayVerifyRouteImport } from './routes/api/razorpay/verify'
import { Route as ApiRazorpayStatusRouteImport } from './routes/api/razorpay/status'
import { Route as ApiRazorpayMarkStatusRouteImport } from './routes/api/razorpay/mark-status'
import { Route as ApiRazorpayCreateOrderRouteImport } from './routes/api/razorpay/create-order'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedAdminWarehouseRouteImport } from './routes/_authenticated/admin.warehouse'
import { Route as AuthenticatedAdminReferralsRouteImport } from './routes/_authenticated/admin.referrals'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminManageImagesRouteImport } from './routes/_authenticated/admin.manage-images'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportPickupRoute = AirportPickupRouteImport.update({
  id: '/airport-pickup',
  path: '/airport-pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartnerRoute = AuthenticatedPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiRazorpayVerifyRoute = ApiRazorpayVerifyRouteImport.update({
  id: '/api/razorpay/verify',
  path: '/api/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayStatusRoute = ApiRazorpayStatusRouteImport.update({
  id: '/api/razorpay/status',
  path: '/api/razorpay/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayMarkStatusRoute = ApiRazorpayMarkStatusRouteImport.update({
  id: '/api/razorpay/mark-status',
  path: '/api/razorpay/mark-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRazorpayCreateOrderRoute = ApiRazorpayCreateOrderRouteImport.update({
  id: '/api/razorpay/create-order',
  path: '/api/razorpay/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminWarehouseRoute =
  AuthenticatedAdminWarehouseRouteImport.update({
    id: '/admin/warehouse',
    path: '/admin/warehouse',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReferralsRoute =
  AuthenticatedAdminReferralsRouteImport.update({
    id: '/admin/referrals',
    path: '/admin/referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminManageImagesRoute =
  AuthenticatedAdminManageImagesRouteImport.update({
    id: '/admin/manage-images',
    path: '/admin/manage-images',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-pickup': typeof AirportPickupRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/admin/manage-images': typeof AuthenticatedAdminManageImagesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/warehouse': typeof AuthenticatedAdminWarehouseRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/mark-status': typeof ApiRazorpayMarkStatusRoute
  '/api/razorpay/status': typeof ApiRazorpayStatusRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-pickup': typeof AirportPickupRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/partner': typeof AuthenticatedPartnerRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/admin/manage-images': typeof AuthenticatedAdminManageImagesRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/admin/warehouse': typeof AuthenticatedAdminWarehouseRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/mark-status': typeof ApiRazorpayMarkStatusRoute
  '/api/razorpay/status': typeof ApiRazorpayStatusRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/airport-pickup': typeof AirportPickupRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/partner': typeof AuthenticatedPartnerRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/_authenticated/admin/manage-images': typeof AuthenticatedAdminManageImagesRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/referrals': typeof AuthenticatedAdminReferralsRoute
  '/_authenticated/admin/warehouse': typeof AuthenticatedAdminWarehouseRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/razorpay/create-order': typeof ApiRazorpayCreateOrderRoute
  '/api/razorpay/mark-status': typeof ApiRazorpayMarkStatusRoute
  '/api/razorpay/status': typeof ApiRazorpayStatusRoute
  '/api/razorpay/verify': typeof ApiRazorpayVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airport-pickup'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/agent'
    | '/partner'
    | '/collections/$slug'
    | '/order/$orderId'
    | '/products/$slug'
    | '/collections/'
    | '/admin/manage-images'
    | '/admin/products'
    | '/admin/referrals'
    | '/admin/warehouse'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/mark-status'
    | '/api/razorpay/status'
    | '/api/razorpay/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airport-pickup'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/agent'
    | '/partner'
    | '/collections/$slug'
    | '/order/$orderId'
    | '/products/$slug'
    | '/collections'
    | '/admin/manage-images'
    | '/admin/products'
    | '/admin/referrals'
    | '/admin/warehouse'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/mark-status'
    | '/api/razorpay/status'
    | '/api/razorpay/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/airport-pickup'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/faq'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/_authenticated/agent'
    | '/_authenticated/partner'
    | '/collections/$slug'
    | '/order/$orderId'
    | '/products/$slug'
    | '/collections/'
    | '/_authenticated/admin/manage-images'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/referrals'
    | '/_authenticated/admin/warehouse'
    | '/api/public/razorpay-webhook'
    | '/api/razorpay/create-order'
    | '/api/razorpay/mark-status'
    | '/api/razorpay/status'
    | '/api/razorpay/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AirportPickupRoute: typeof AirportPickupRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiRazorpayCreateOrderRoute: typeof ApiRazorpayCreateOrderRoute
  ApiRazorpayMarkStatusRoute: typeof ApiRazorpayMarkStatusRoute
  ApiRazorpayStatusRoute: typeof ApiRazorpayStatusRoute
  ApiRazorpayVerifyRoute: typeof ApiRazorpayVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-pickup': {
      id: '/airport-pickup'
      path: '/airport-pickup'
      fullPath: '/airport-pickup'
      preLoaderRoute: typeof AirportPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/partner': {
      id: '/_authenticated/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof AuthenticatedPartnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/razorpay/verify': {
      id: '/api/razorpay/verify'
      path: '/api/razorpay/verify'
      fullPath: '/api/razorpay/verify'
      preLoaderRoute: typeof ApiRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/status': {
      id: '/api/razorpay/status'
      path: '/api/razorpay/status'
      fullPath: '/api/razorpay/status'
      preLoaderRoute: typeof ApiRazorpayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/mark-status': {
      id: '/api/razorpay/mark-status'
      path: '/api/razorpay/mark-status'
      fullPath: '/api/razorpay/mark-status'
      preLoaderRoute: typeof ApiRazorpayMarkStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/razorpay/create-order': {
      id: '/api/razorpay/create-order'
      path: '/api/razorpay/create-order'
      fullPath: '/api/razorpay/create-order'
      preLoaderRoute: typeof ApiRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/warehouse': {
      id: '/_authenticated/admin/warehouse'
      path: '/admin/warehouse'
      fullPath: '/admin/warehouse'
      preLoaderRoute: typeof AuthenticatedAdminWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/referrals': {
      id: '/_authenticated/admin/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AuthenticatedAdminReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/manage-images': {
      id: '/_authenticated/admin/manage-images'
      path: '/admin/manage-images'
      fullPath: '/admin/manage-images'
      preLoaderRoute: typeof AuthenticatedAdminManageImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedPartnerRoute: typeof AuthenticatedPartnerRoute
  AuthenticatedAdminManageImagesRoute: typeof AuthenticatedAdminManageImagesRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminReferralsRoute: typeof AuthenticatedAdminReferralsRoute
  AuthenticatedAdminWarehouseRoute: typeof AuthenticatedAdminWarehouseRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedPartnerRoute: AuthenticatedPartnerRoute,
  AuthenticatedAdminManageImagesRoute: AuthenticatedAdminManageImagesRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminReferralsRoute: AuthenticatedAdminReferralsRoute,
  AuthenticatedAdminWarehouseRoute: AuthenticatedAdminWarehouseRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AirportPickupRoute: AirportPickupRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiRazorpayCreateOrderRoute: ApiRazorpayCreateOrderRoute,
  ApiRazorpayMarkStatusRoute: ApiRazorpayMarkStatusRoute,
  ApiRazorpayStatusRoute: ApiRazorpayStatusRoute,
  ApiRazorpayVerifyRoute: ApiRazorpayVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
