export { ProductCard } from "./ProductCard";
export { ProductCardSkeleton } from "./ProductCardSkeleton";
export { RecommendationCarousel } from "./RecommendationCarousel";
export { RecommendationSection } from "./RecommendationSection";
export type { RecommendationSectionProps } from "./RecommendationSection";
export { YouMightAlsoLike } from "./YouMightAlsoLike";
export { PeopleAlsoViewed } from "./PeopleAlsoViewed";
export { formatPrice } from "./formatPrice";
export { youMightAlsoLikeSample, peopleAlsoViewedSample } from "./sampleProducts";
export type { RecommendedProduct, RecommendationLayout } from "./types";
